stages:
  train:
    cmd: python3 src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/train_data.csv
    outs:
      - models/model.pkl

  eval:
    cmd: python3 src/models/predict_model.py
    deps:
      - src/models/predict_model.py
      - models/model.pkl
    outs:
      - reports/evaluation.txt

  process_data:
    cmd: python3 src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw/PS_20174392719_1491204439457_log.csv
    outs:
      - data/processed/train_data.csv
