name: pre-commit

on:
  pull_request:
  push:
    branches: [] # Sin restricciones de rama

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        node-version: '20'


    - name: Checkout Python
      uses: actions/setup-python@v4

    - name: Pre-commit actions
      uses: pre-commit/action@v3.0.1

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pylint

    - name: Run pre-commit hooks
      run: pre-commit run --all-files


    - name: Run Python Custom Tests
      run: |
          python tests/test_integration.py
          python tests/test_utils.py
